using AutoMapper;
using PawNest.DAL.Data.Entities;
using PawNest.DAL.Data.Requests.Pet;
using PawNest.DAL.Data.Responses.Pet;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PawNest.DAL.Mappers
{
    public class PetMapper : Profile
    {
        public PetMapper()
        {
            // CreatePetRequest to Pet
            CreateMap<CreatePetRequest, Pet>()
                .ForMember(dest => dest.PetId, opt => opt.Ignore()) // Id will be generated by the database
                .ForMember(dest => dest.Owner, opt => opt.Ignore()) // OwnerId will be set manually
                .ForMember(dest => dest.Bookings, opt => opt.Ignore()); // Ignore navigation properties
            
            

            // CreatePetResponse
            CreateMap<Pet, CreatePetResponse>()
                .ForMember(dest => dest.PetName, opt => opt.MapFrom(src => src.PetName))
                .ForMember(dest => dest.Breed, opt => opt.MapFrom(src => src.Breed))
                .ForMember(dest => dest.Species, opt => opt.MapFrom(src => src.Species));
                
        }
    }
}
